openapi: 3.0.0
info:
  title: SAAGIS API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.2.0

servers:
  - url: /alumni/
    description: List of alumni in the university
  - url: /lectures/
    description: List of lectures in the university
  - url: /history/
    description: History of a given alumni

paths:
  /:
    get:
      summary: Returns a list of the university alumni.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of alumni names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /<int:id>:
    get:
      summary: Returns info by alumni_id.
      description: alumni_id columns.
      responses:
        '200':  # status code
          description: A JSON array of the alumni_id data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
